(cl:defpackage SubImageRecognition-srv
  (:use )
  (:export
   "SWITCHALGORITHM"
   "<SWITCHALGORITHM-REQUEST>"
   "SWITCHALGORITHM-REQUEST"
   "<SWITCHALGORITHM-RESPONSE>"
   "SWITCHALGORITHM-RESPONSE"
   "LISTALGORITHMS"
   "<LISTALGORITHMS-REQUEST>"
   "LISTALGORITHMS-REQUEST"
   "<LISTALGORITHMS-RESPONSE>"
   "LISTALGORITHMS-RESPONSE"
  ))

