/* Auto-generated by genmsg_cpp for file /opt/robosub/rosWorkspace/SubImageRecognition/msg/OrangeRectangle.msg */
#ifndef SUBIMAGERECOGNITION_MESSAGE_ORANGERECTANGLE_H
#define SUBIMAGERECOGNITION_MESSAGE_ORANGERECTANGLE_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"


namespace SubImageRecognition
{
template <class ContainerAllocator>
struct OrangeRectangle_ : public ros::Message
{
  typedef OrangeRectangle_<ContainerAllocator> Type;

  OrangeRectangle_()
  : stamp()
  , center_x(0)
  , center_y(0)
  , rotation(0.0)
  , confidence(0.0)
  {
  }

  OrangeRectangle_(const ContainerAllocator& _alloc)
  : stamp()
  , center_x(0)
  , center_y(0)
  , rotation(0.0)
  , confidence(0.0)
  {
  }

  typedef ros::Time _stamp_type;
  ros::Time stamp;

  typedef uint16_t _center_x_type;
  uint16_t center_x;

  typedef uint16_t _center_y_type;
  uint16_t center_y;

  typedef float _rotation_type;
  float rotation;

  typedef float _confidence_type;
  float confidence;


private:
  static const char* __s_getDataType_() { return "SubImageRecognition/OrangeRectangle"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "f4d874cbf5602fc8af32db3aa825d47e"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "time stamp\n\
uint16 center_x\n\
uint16 center_y\n\
float32 rotation\n\
float32 confidence\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, stamp);
    ros::serialization::serialize(stream, center_x);
    ros::serialization::serialize(stream, center_y);
    ros::serialization::serialize(stream, rotation);
    ros::serialization::serialize(stream, confidence);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, stamp);
    ros::serialization::deserialize(stream, center_x);
    ros::serialization::deserialize(stream, center_y);
    ros::serialization::deserialize(stream, rotation);
    ros::serialization::deserialize(stream, confidence);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(stamp);
    size += ros::serialization::serializationLength(center_x);
    size += ros::serialization::serializationLength(center_y);
    size += ros::serialization::serializationLength(rotation);
    size += ros::serialization::serializationLength(confidence);
    return size;
  }

  typedef boost::shared_ptr< ::SubImageRecognition::OrangeRectangle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::SubImageRecognition::OrangeRectangle_<ContainerAllocator>  const> ConstPtr;
}; // struct OrangeRectangle
typedef  ::SubImageRecognition::OrangeRectangle_<std::allocator<void> > OrangeRectangle;

typedef boost::shared_ptr< ::SubImageRecognition::OrangeRectangle> OrangeRectanglePtr;
typedef boost::shared_ptr< ::SubImageRecognition::OrangeRectangle const> OrangeRectangleConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::SubImageRecognition::OrangeRectangle_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::SubImageRecognition::OrangeRectangle_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace SubImageRecognition

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::SubImageRecognition::OrangeRectangle_<ContainerAllocator> > {
  static const char* value() 
  {
    return "f4d874cbf5602fc8af32db3aa825d47e";
  }

  static const char* value(const  ::SubImageRecognition::OrangeRectangle_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xf4d874cbf5602fc8ULL;
  static const uint64_t static_value2 = 0xaf32db3aa825d47eULL;
};

template<class ContainerAllocator>
struct DataType< ::SubImageRecognition::OrangeRectangle_<ContainerAllocator> > {
  static const char* value() 
  {
    return "SubImageRecognition/OrangeRectangle";
  }

  static const char* value(const  ::SubImageRecognition::OrangeRectangle_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::SubImageRecognition::OrangeRectangle_<ContainerAllocator> > {
  static const char* value() 
  {
    return "time stamp\n\
uint16 center_x\n\
uint16 center_y\n\
float32 rotation\n\
float32 confidence\n\
\n\
";
  }

  static const char* value(const  ::SubImageRecognition::OrangeRectangle_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::SubImageRecognition::OrangeRectangle_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::SubImageRecognition::OrangeRectangle_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.stamp);
    stream.next(m.center_x);
    stream.next(m.center_y);
    stream.next(m.rotation);
    stream.next(m.confidence);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct OrangeRectangle_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::SubImageRecognition::OrangeRectangle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::SubImageRecognition::OrangeRectangle_<ContainerAllocator> & v) 
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "center_x: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.center_x);
    s << indent << "center_y: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.center_y);
    s << indent << "rotation: ";
    Printer<float>::stream(s, indent + "  ", v.rotation);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
  }
};


} // namespace message_operations
} // namespace ros

#endif // SUBIMAGERECOGNITION_MESSAGE_ORANGERECTANGLE_H

