"""autogenerated by genmsg_py from OrangeRectangle.msg. Do not edit."""
import roslib.message
import struct

import roslib.rostime

class OrangeRectangle(roslib.message.Message):
  _md5sum = "2ada05e34d1ee5ab63cd781bf91803ce"
  _type = "SubImageRecognition/OrangeRectangle"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """time stamp
uint16 center_x
uint16 center_y
float32 rotation

"""
  __slots__ = ['stamp','center_x','center_y','rotation']
  _slot_types = ['time','uint16','uint16','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       stamp,center_x,center_y,rotation
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(OrangeRectangle, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.stamp is None:
        self.stamp = roslib.rostime.Time()
      if self.center_x is None:
        self.center_x = 0
      if self.center_y is None:
        self.center_y = 0
      if self.rotation is None:
        self.rotation = 0.
    else:
      self.stamp = roslib.rostime.Time()
      self.center_x = 0
      self.center_y = 0
      self.rotation = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_2I2Hf.pack(_x.stamp.secs, _x.stamp.nsecs, _x.center_x, _x.center_y, _x.rotation))
    except struct.error, se: self._check_types(se)
    except TypeError, te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      if self.stamp is None:
        self.stamp = roslib.rostime.Time()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.stamp.secs, _x.stamp.nsecs, _x.center_x, _x.center_y, _x.rotation,) = _struct_2I2Hf.unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_2I2Hf.pack(_x.stamp.secs, _x.stamp.nsecs, _x.center_x, _x.center_y, _x.rotation))
    except struct.error, se: self._check_types(se)
    except TypeError, te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      if self.stamp is None:
        self.stamp = roslib.rostime.Time()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.stamp.secs, _x.stamp.nsecs, _x.center_x, _x.center_y, _x.rotation,) = _struct_2I2Hf.unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_2I2Hf = struct.Struct("<2I2Hf")
